{{- if .Values.projectionDefinitionIdMappings }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "osdcdrillingfieldservice.fullname" . }}-projection-mappings
  labels:
    {{- include "osdcdrillingfieldservice.labels" . | nindent 4 }}
data:
  Field.ProjectionMappings.json: |-
    {
      "ProjectionDefinitionIdMappings": {{ .Values.projectionDefinitionIdMappings | toJson }}
    }
{{- end }}
